Add tokenKeyUrl to sample Google OIDC config
Prior to our v251 to v253 CF upgrade, logging in with google OpenID Connect
seemed to be working, however once we'd upgraded to v253 we encountered the
error: "There was an error when authenticating against the external identity
provider: Could not verify token signature."

As suggested in https://github.com/cloudfoundry/uaa/issues/565, a tokenKeyURL
has been added.  https://www.googleapis.com/oauth2/v3/certs was used instead of
the URL suggested there, as this is the URL returned from
https://accounts.google.com/.well-known/openid-configuration