fix: ErrorRoutingIT test (#2977)
* fix: ErrorRoutingIT test failure message

- correct the order of actual vs. expected, such that
the test failure message is correct
- before this commit, the failure message is:
```
java.lang.AssertionError: Check status code from /error429 is 200 expected:<429> but was:<200>
```
which is not correct

* fix: ErrorRoutingIT

- the test is intended to access /error429 as a browser would
and expects a 200 response (due to this request mapping:
https://github.com/cloudfoundry/uaa/blob/0a28b5c5aa33c68a5cdb20f23812d5187135b4a8/server/src/main/java/org/cloudfoundry/identity/uaa/home/HomeController.java#L155 and NOT https://github.com/cloudfoundry/uaa/blob/0a28b5c5aa33c68a5cdb20f23812d5187135b4a8/server/src/main/java/org/cloudfoundry/identity/uaa/home/HomeController.java#L144)

- however, in some environments where this test is run, the test
does not access the /error429 like a browser would (e.g. does not
have the request header "Accept: text/html" by default), so explictly
adding this header to the test setup to better emulate a browser
request