Fix ldap test
The `authenticated()` matcher no longer works now that we have added
spring session, yielding this error:

```
java.lang.AssertionError: Authentication should not be null
```

[#167949908]

Signed-off-by: Stephane Jolicoeur <sjolicoeur@pivotal.io>
Co-authored-by: Stephane Jolicoeur <sjolicoeur@pivotal.io>
Signed-off-by: Stephane Jolicoeur <sjolicoeur@pivotal.io>
Co-authored-by: Stephane Jolicoeur <sjolicoeur@pivotal.io>