fix: ErrorRoutingIT test failure message
- correct the order of actual vs. expected, such that
the test failure message is correct
- before this commit, the failure message is:
```
java.lang.AssertionError: Check status code from /error429 is 200 expected:<429> but was:<200>
```
which is not correct